name: pull-request

on: [pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Copyright	
      run: |
        mvn license:check
    - name: Build and Test	
      run:
        mvn clean verify

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

